name: Bug Report
description: Report a bug, crash, or other type of error with these scripts
type: Bug
body:
  - id: validation
    type: checkboxes
    attributes:
      label: Validation
      options:
      - label: I have checked the [Issues](https://github.com/Twanvanb1/Usefull-RSDK-Scripts/issues) page to see if my problem has already been reported
        required: true
      - label: I have confirmed that this bug does not occur in the original game
        required: false
  - id: describe-bug
    type: textarea
    validations:
      required: true
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
  - id: repro-steps
    type: textarea
    validations:
      required: true
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions on how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. etc.
  - id: expected-behavior
    type: textarea
    validations:
      required: true
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - id: specs-os
    type: input
    validations:
      required: true
    attributes:
      label: Operating System
      description: The name of the operating system you are running (e.g. **Windows 10**, **Windows 11**, **Linux distro**).
  - id: additional-context
    type: textarea
    validations:
      required: false
    attributes:
      label: Additional Context
      description: Provide any other context about the problem here.
